services:
    dev:
        container_name: dev
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        volumes:
            - .:/app
        ports:
            - "8000:8000"
