name: Deploy to Netlify

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.5

      - name: Install dependencies
        run: pnpm install

      - name: Create dist directory
        run: mkdir dist

      - name: Build for production
        run: pnpm build:app
