name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.5

      - name: Install dependencies
        run: pnpm install

      - name: Build for production
        run: pnpm build:app

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.1
        with:
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist

          # Configure custom domain using CNAME file (optional)
          # artifacts: 'dist/**/*'  # Optional if you want to upload everything in dist folder
          # CNAME_FILE: 'dist/CNAME'  # Optional, path to your CNAME file (if it's not in the root)

env:
  # Required to deploy to GitHub Pages
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
